feathersjs/docs

SUMMARY.md
databases/extending.md
databases/knexjs.md
databases/memory.md
databases/mongoose.md
databases/nedb.md
databases/pagination.md
databases/querying.md
databases/readme.md
databases/sequelize.md
databases/waterline.md
services/readme.md

Documentation for all database adapters which are now referencing those pages in their docs.

Database docs

---

SUMMARY.md
authentication/readme.md
authorization/bundled-hooks.md
authorization/readme.md

This is a healthy update to the Authorization section and includes a separate page documenting the bundled hooks.  It also includes all information that was previously on the `feathers-authentication` README.md.

Authorization section overhaul.

---

hooks/readme.md

Still need to add bundled hooks but that is still in flux as to what we are including and what we aren't.

adding feathers hooks docs

---

authentication/local.md
authentication/oauth2.md
authentication/readme.md
authentication/token.md
authorization/bundled-hooks.md

This is dependent on https://github.com/feathersjs/feathers-authentication/pull/70.

updating authentication config docs

---

SUMMARY.md
databases/knexjs.md
databases/memory.md
databases/mongodb.md
databases/mongoose.md
databases/nedb.md
databases/sequelize.md
databases/waterline.md

Updating database examples to use the "messages" instead of todos so that it feels more familiar to the demo app. Fixed a bunch of other inconsistencies and some typos.

Database consistency

---

guides/angular2.md

I created an Angular 2 guide. There's not a ton of feathers-specific content in there because it's so simple to setup. Instead, I detail the service structure that I recommend for feathers and a few of the strange Angular-y issues users are likely to run in to.
Really my code is nothing that anyone past an Angular novice couldn't figure out for themselves, so I kept it pretty lightweight and tried to explain things thoroughly.
I didn't edit super heavily so there could be some errors in it as well. Let me know what you think.

Initial version of the angular2 guide

---

why/vs/meteor.md

A license is either Open Source (it meets the OSD) or is not. There is no 'completely open source'. 
PR sent per your comment at https://news.ycombinator.com/item?id=11304380

Fix 'completely open source'

---

middleware/routing.md

Fixed spelling error "calllback" to "callback"

Update routing.md spelling error

---

why/philosophy.md

Add an `e` to `fatures.md` to resolve 404 error.

Correct 404 error.

---

guides/react.md

This will show a random image from this url: https://placeimg.com/60/60/people.  It will change every time the page is loaded, but I think it's better than a broken image.

Fix the react placeholder.

---

getting-started/formatting-and-hooks.md
getting-started/user-management.md
guides/react.md

This makes the necessary changes for upgrading the auth plugin to version 0.6.0.  It also includes some slight rewording to make it easier to read.  Also added a small edit to the react guide.

Get the guide ready for auth@0.6.0

---

authentication/client.md
clients/feathers.md
clients/primus.md
clients/rest.md
clients/socket-io.md
getting-started/scaffolding.md
guides/jquery.md
guides/react.md

Adding note and script tags to include ES6 polyfills

---

why/vs/meteor.md

update primus link on meteor vs page

---

getting-started/user-management.md

Closes https://github.com/feathersjs/feathers/issues/298

Clarification on when chat.html will be implemented

---

help/faq.md

After all the other related issues are closed this will close https://github.com/feathersjs/feathers-socket-commons/issues/10

Add FAQ item for maxListener warning

---

getting-started/scaffolding.md

For more details, see [issue 78 in feathers-generator](https://github.com/feathersjs/generator-feathers/issues/78).

Added pro-tip on using latest node/npm

---

getting-started/formatting-and-hooks.md

Fixes broken avatar support in frontend frameworks

---

frameworks/jquery.md
hooks/bundled.md
middleware/error-handling.md

Closing the issues referenced in the commits.

Some documentation updates

---

getting-started/quick-start.md
getting-started/readme.md
guides/setting-up.md

Adding a setting up guide for Node and Babel

---

frameworks/vuejs.md

Initial implementation of the Vue.js docs to coincide with the Feathers & Vue.js chat example.

Implements Vuejs docs

---

frameworks/vuejs.md

Adds missing documentation and fixes #151 
None.
* Chrome v.49 (Mac OS X 10.11.3) [Macbook Air].
* Firefox v.44.0.2 (Mac OS X 10.11.3) [Macbook Air]

Adds missing Vue component init

---

frameworks/vuejs.md

Getting the app.service for `userService` and `messageService` are missing.

Missing to app.service call

---

guides/creating-a-plugin.md

References issue https://github.com/feathersjs/feathers-docs/issues/155

Basic plugin creation doc

---

getting-started/setting-up.md

Adding colon so those who copy-paste have valid JSON.

Missing colon

---

authorization/readme.md

I just noticed this little mistake in the comment while reading the doc, it must of been forgotten when you guys made changes to the auth :)

Comment wasn't up to date with the changes of auth

---

getting-started/formatting-and-hooks.md

`hook` should be plural, `hooks`

Fix file name

---

getting-started/setting-up.md

Referenced command from [https://babeljs.io/docs/setup/](https://babeljs.io/docs/setup/#installation)

Added test command that works with ES2015 (Babel)

---

authentication/client.md

LOL, I leave out 'r' all the time :)

added 'r' to the word 'you' for the Login section.

---

databases/pagination.md

Closes https://github.com/feathersjs/feathers/issues/219

Adding documentation for setting pagination options

---

frameworks/vuejs.md

Earlier in the file, the docs assume user to create `public/chat.html` HTML file. But later, the docs referencing to `index.html`, not `chat.html`.

Change mentioned `index.html` to `chat.html`

---

frameworks/react.md

For a better display in gitbook

Change syntax highlighting to javascript

---

testing/readme.md

Added test/readme.md containing a tutorial on how to test using Mocha/Chai and deal with authentication.

Addition of test/readme.md

---

authorization/bundled-hooks.md

Adds documentation for hasRoleOrRestrict, verifyOrRestrict, and populateOrRestrict.

Adds documentation for restriction methods.

---

authentication/client.md

Please see https://github.com/feathersjs/feathers-authentication/pull/278

Addition of 'endpoint' option

---

getting-started/quick-start.md

For the convenience of users familiar with Postman.

Add "Run in Postman" button for messages service

---

SUMMARY.md
frameworks/choo.md
getting-started/frontend.md

relevant for 7c61b43 and related to feathersjs/feathers-chat#30

add feathers-chat choo client documentation page and frontend summary refs

---

why/vs/parse.md

Some paragraphs have been corrected, but the result makes parse-server more similar to Feathers, so maybe we can remove some parts of this text. Closes https://github.com/feathersjs/feathers/issues/411

correct parse-server mistakes

---

clients/feathers.md

Added `/socket.io` to `import io from 'socket.io-client';`

Fix "io" import statement

---

databases/pagination.md

Just changed the header and intro paragraph to mention selecting so people can find it easier ..

Minor editorial tweaks to include $select in header

---

guides/file-uploading.md

The *Our Goals* section rang somwhat oddly, with a mix of present and future verb tenses.  Also some “filler” words could be removed without affecting clarity.
So here the *Our Goals* section is a little tighter, and a little more consistent.

Tighten-up file uploading section, goals subsection.

---

testing/readme.md

Path before editing: src/services/menu/user-model.js
Path now: src/services/user/user-model.js

Fix the path to user-model.js

---

hooks/common_hooks.md
hooks/validation.md

Please check out the format, etc. Comments are welcome.
I noticed someplace that someone posted a todo about documenting how to validate with hooks. I added a validation.md because I felt an example was needed to properly document the value of the validate hook.

Added docs for feathers-hooks-common

---

clients/vanilla-rest.md

Just expanded the documentation with some more (slightly) complex style FIND queries and introduced here the qs() option to make even more complex queries possible via the URL.

More examples of REST Calls

---

databases/knexjs.md

Very minor PR: Adjust the list of databases to match those enumerated at http://knexjs.org.

KnexJS also supports MSSQL.  

---

databases/querying.md

Also, like in the Pagination and Sorting page’s ProTip, enumerate the tokens to avoid.

Consistent referencing of the “Pagination and Sorting” page.

---

SUMMARY.md
hooks/bundled.md
why/showcase.md

- Added common hooks to summary.md
- Added deprecated notice added to bundled.md
- Added live-query example to showcase.md
- Minor change in showcase.md to force 2 lines which don't appear
in GitBook.

Minor changes to GitBook

---

databases/knexjs.md

See also https://github.com/feathersjs/feathers-knex/pull/79

Add $like documentation for knex

---

configuration/readme.md

We need to update the docs for [feathers-configuration](https://docs.feathersjs.com/configuration/readme.html) to account for the changes in feathersjs/feathers-configuration#27

Update documentation for feathers-config

---

authentication/token.md

Fix some typo in the docs

---

frameworks/vuejs.md

Hey guys, not much to say here, I simply updated the guide to use Vue2.0 compatible syntax.
If there's any questions, shoot em.
PS: I have one of my own: should I also submit this PR for the auk branch or will you guys merge this in later?

Updating frameworks/vuejs with Vue 2.0 Syntax

---

getting-started/scaffolding.md

Add missing word. Split up sentence for readability. Punctuation.

Minor grammatical edits

---

SUMMARY.md
guides/seeding-services.md

[`feathers-seeder](https://github.com/thosakwe/feathers-seeder) is a package I made a few months ago, and recently polished up and released v1.0.0. I think that many people would find it convenient, so I published a small guide.
Thanks if you decide to accept!

Seeding Services - Guide

---

databases/rethinkdb.md

Create 'messages' as a table instead of a database

Fix RethinkDB documentation example

---

hooks/common.md

Fixed populate example

---

getting-started/scaffolding.md

There were a few minor things I got tripped up on, but were easily overcome (for me). Thought I'd suggest edits to help the next guy through more smoothly.

A Few Edits from a Beginner

---

why/showcase.md

This is a project I was hired to build several months ago, I think it might serve as a nice example of what you can build with Feathers.

Add https://jabpi.com to showcase

---

rest/readme.md

Added a protip about qs and arrays

---

databases/knexjs.md

For https://github.com/feathersjs/feathers-knex/issues/87 and https://github.com/feathersjs/feathers-knex/pull/88

Update KnexJS documentation

---

databases/mongodb.md

mongodb.md required installations fix

---

.gitignore
hooks/bundled-deprecated.md

https://github.com/feathersjs/feathers-docs/issues/322

Wrong package name "feathers-hooks-common" in docs 

---

getting-started/quick-start.md

You have a video example by Chris Pena, but unfortunately he never completed his video series... he never even got passed the first lecture video. It leaves a lot of people hanging, and does not help your adoption efforts.
Ben Awad on the other hand, produced 8 videos, an entire series, on how to get up and running with FeatherJS. I have no affiliation with him, but I am going through his series, and it's top notch, and I recommend his videos to remove the friction from adopting a new library!
I'm more likely to adopt feathers now, because of Ben Awad. I almost abandoned FeathersJS because Chris Pena's video series was incomplete.

Ben Awad just published a Full Example on YouTube

---

getting-started/quick-start.md

I changed it from this one (broken):
https://www.youtube.com/playlist?list=PLN3n1USn4xlnulnnBGD2RMid_p7xVj9x
to this one (working):
https://www.youtube.com/playlist?list=PLN3n1USn4xlnulnnBGD2RMid_p7xVj9xU

Current Playlist Points to a Broken Link

---

hooks/common/conditional.md

- 5 new hooks have to be documented
- The new sectioning makes it easy to see what the hooks are for
- Placeholders opnly added for when, unless, some, every

Added sections to conditional hooks page

---

hooks/common/conditional.md

- They all allow a predicate that is a boolean, Promise or func
- Docs only mentioned func

Fixed docs for iffElse, iff, isNot

---

SUMMARY.md
hooks/common/altering-data.md
hooks/common/populate.md

- Added subpage hooks/common/populate.md.
- Docs are from feathers-hooks-populate README already reviewed.
- Remove docs for legacy populate.

Added docs for populate, serialize, dePopulate

---

frameworks/choo.md

Fix typo "fethers" =>  "feathers"

---

authentication/management.md

@eddyystop please check out these few edits I made to make sure they make sense.

Typo fixes and clarifications

---

authentication/readme.md

Typo fix in authentication/readme

---

getting-started/formatting-and-hooks.md

updated link to hooks

---

SUMMARY.md
scaling/readme.md

I wrote up the beginnings of some scaling documentation. I cover horizontal scaling via clustering. Eventually it would be ideal to describe how to scale across multiple machines with a load balancer.

Scaling documentation

---

SUMMARY.md
package.json
styles/website.css

- Using v3.0.0 of Feathers customized TOC plugin
- Changed SUMMARY as required
- Added styling to styles/website.css
- >>> No idea how this affects printed docs
- Bumped package.json version

Changes Guide section TOC as discussed

---

frameworks/angular2.md

feathersjs/feathers#381 angular2 docs

improve docs based on added typescript support

---

api/client.md
ecosystem/README.md
guides/chat/client/other-clients.md
guides/chat/client/readme.md

Fixes a couple typos and adds Client APi docs.
Also adds feathers-vuex to the Ecosystem page.

Auk reorg client

---

api/hooks-common.md

- Added docs for discard and deleteByDot.
- Changed example to use ES^ object destructuring.
- Corrected some example still referring to subfolders.

Brought common hooks doc up-to-date

---

frameworks/nuxtjs.md

This PR adds a guide for creating Feathers + Nuxt applications.

Add Nuxt guide

---

guides/auth/readme.md
guides/readme.md

I don’t think we should sell this as an advanced topic.  We’ve made auth easy.  So it gets its own, separate section.

Adds an Auth Guides section

---

SUMMARY.md
api/authentication/hooks.md

Depends on https://github.com/feathersjs/feathers-authentication-hooks/pull/4 and the module being released. Then we can update the generator accordingly and I can finish the last bit of the chat guide.

Adding documentation for feathers-authentication-hooks package

---

faq/readme.md

- Closes https://github.com/feathersjs/feathers-docs/issues/428
- Closes https://github.com/feathersjs/feathers-docs/issues/429
- Closes https://github.com/feathersjs/feathers-docs/issues/432
- Closes https://github.com/feathersjs/feathers-docs/issues/433
- Closes https://github.com/feathersjs/feathers-docs/issues/434
- Closes https://github.com/feathersjs/feathers-docs/issues/435
- Closes https://github.com/feathersjs/feathers-docs/issues/436

Finalize the FAQ section for now

---

guides/step-by-step/preliminaries.md

Looks like the writer missed a word here 🤓

Typos / missing word

---

guides/auth/recipe.oauth-basic.md

I picked "for", feel free to choose "to"!
- https://forum.wordreference.com/threads/point-to-the-need-to-or-for.2660720/
- https://english.stackexchange.com/questions/6623/need-of-vs-need-for

The need to or the need for?

---

ecosystem/readme.md

Since [you were so kind to invite me to do so](https://twitter.com/feathersjs/status/853082460707581953), here's the PR ^_^

Adds `feathers-hooks-jsonapify` to Transformation

---

api/authentication/hooks.md
faq/readme.md

Adding FAQ on how to do search

---

api/socketio.md

Word feathers Fixed

---

api/socketio.md

https://github.com/feathersjs/feathers-socketio/pull/66
https://github.com/feathersjs/feathers-socketio/pull/69

Attach socket.io server to a separate port

---

api/socketio.md

Fix Word feathers

---

faq/readme.md

Fleshing out the custom routing FAQ entry a little more from the discussion in https://github.com/feathersjs/feathers/pull/141

Adding some more content to the routing FAQ

---

api/authentication/oauth1.md
api/authentication/oauth2.md
api/authentication/server.md
api/databases/rethinkdb.md
api/express.md

Open changes discovered in #540

Additional tweaks for #540

---

guides/step-by-step/basic-feathers/real-time.md
guides/step-by-step/readme.md

Closes https://github.com/feathersjs/feathers-guide/issues/9

Fix casing for links

---

guides/step-by-step/basic-feathers/database-connector.md
guides/step-by-step/basic-feathers/rest-api-server.md
guides/step-by-step/basic-feathers/rest-client.md
guides/step-by-step/generators/gen-app.md
guides/step-by-step/generators/readme.md
guides/step-by-step/intro/readme.md
guides/step-by-step/preliminaries.md

I had reason to read some of the docs, so I fixed some typos and made some minor tweaks.

Documentation tweaks -- typo fixes, minor rewording

---

api/databases/mongodb.md

- Closes https://github.com/feathersjs/feathers/issues/563
- Closes https://github.com/feathersjs/feathers-mongodb/pull/87
- Closes https://github.com/feathersjs/feathers-rest/pull/112

Add note to MongoDB documentation to convert query values

---

api/databases/mongoose.md

Documentation for https://github.com/feathersjs/feathers-mongoose/pull/180.

Mongoose Discriminator Docs

---

api/hooks-common.md

reflects the api change discussed in https://github.com/feathersjs/feathers-hooks-common/issues/154

update validate-schema in hooks-common

---

guides/step-by-step/basic-feathers/rest-client.md

Quick small fix, thanks for all the work on the docs ^^.

Missing slashes on code snippet

---

ecosystem/readme.md

BeachfrontDigital is now live.

Added new production application

---

ecosystem/readme.md

I've published a tutorial on www.sitepoint.com that shows users how to develop a CRUD app using Feathers + React + Redux.

Build a CRUD App Using React, Redux and FeathersJS

---

api/databases/sequelize.md

This coincides with https://github.com/feathersjs/feathers-sequelize/pull/106

Add documentation about `raw` queries

---

ecosystem/readme.md

Aurelia app (built with Aurelia-CLI) connected to Feathers server application via websockets (socket.io)

aurelia feathersjs socket demo application

---

api/hooks-common.md

- See https://github.com/feathersjs/feathers-hooks-common/issues/140

Added warning to avoid an issue with iff, else, iffElse hooks.

---

guides/chat/authentication.md

Fixed "messsages" to "messages"

Spelling error

---

examples/chat/client/jquery/public/client.html
examples/chat/server/client/public/socketio.html
examples/chat/server/finish/public/socketio.html
examples/step/01/common/public/listener.html
examples/step/01/common/public/rest-del.html
examples/step/01/common/public/rest.html
examples/step/01/common/public/socketio.html
examples/step/_diff/01-websocket-socketio-line.html
guides/step-by-step/basic-feathers/rest-client.md
guides/step-by-step/basic-feathers/socket-client.md

- Some Chrome versions insist on http://cdnjs and https://unpkg
Resolves https://github.com/feathersjs/feathers-docs/issues/572

Fixed URLs in The Basics and Generator

---

api/databases/elasticsearch.md

This changes are pertaining [PR#16](https://github.com/feathersjs/feathers-elasticsearch/pull/16) on feathers-elasticsearch.

docs(elasticsearch) add `$all` query description

---

api/hooks-common.md

see https://github.com/feathersjs/feathers-hooks-common/pull/176

update api/hooks-common/iff|else with array syntax

---

guides/step-by-step/basic-feathers/real-time.md

Closes https://github.com/feathersjs/feathers-docs/issues/603

Clarified filter example in The Basics - realtime #603

---

ecosystem/readme.md

- Added ecosystem link to Feathers SDK

Feathers Swift docs

---

ecosystem/readme.md

Added a sample (which could be used as a starter) for Feathers + Nuxt apps

Added feathers-nuxt to the list

---

api/hooks-common.md

Resolves https://github.com/feathersjs/feathers-hooks-common/issues/187

Documented how to use populate without using parentField & childField

---

ecosystem/readme.md

Adds https://github.com/codingfriend1/Feathers-Vue to FeathersJS ecosystem.

Adds Feathers Vue to ecosystem.

---

examples/step/01/db-connector/3.js
examples/step/01/package.json

Hi featherjs developers,
I like to support you with your wonderful framework. Here is a small bug fix that avoid a "undefined" and a missing dependencies error message.
Best Regards,
Zaher

Bug fix: postgres example in step 01

---

examples/step/01/common/public/feathers-app-del.js
examples/step/01/common/public/feathers-app.js
examples/step/01/hooks/1.js
examples/step/01/hooks/2.js
guides/step-by-step/basic-feathers/hooks-1.md
guides/step-by-step/basic-feathers/hooks-2.md

Fixes the example code referenced in the documentation for hooks (part 1 & part 2).
Fixes #645.

Fix hooks docs

---

README.md
SUMMARY.md

It seems to have been accidentally dropped from SUMMARY.md here: https://github.com/feathersjs/feathers-docs/commit/3e1bb1e51cb07e6a8eb865cc73fd5479a6dc4457#diff-b4f3573b2f24d5af026c33acf52ff716L142
I added a summary to README.md as well.

Re-add the security page

---

guides/chat/authentication.md

Documented how to setup authentication inside the chat application

---

api/hooks-common.md

A couple things I want to be clarified though before I attempt to make more things consistent in the examples:
- Implicit (invisible/omitted) or explicit imports of hooks?
- Import specific hooks, the default `hooks` or even both?
- ES5 or ES6 imports?

Fix typo and slightly improve example consistency

---

api/databases/elasticsearch.md

For PR on elasticsearch adapter - https://github.com/feathersjs/feathers-elasticsearch/pull/24

Added documentation for the simple_query_string

---

api/databases/elasticsearch.md

Shrunk the $default_operator to be just $operator
Signed-off-by: Matt <matt@ideajunction.uk>

Changed the syntax for operator

---

api/authentication/client.md

Related to https://github.com/feathersjs/feathers/issues/579

Added mention of initialization order

---

guides/step-by-step/basic-feathers/writing-hooks.md

Not sure if this helps anyone else but I was initially confused.

Small clarification

---

api/authentication/keystone.md
ecosystem/readme.md

As it was discussed with @marshallswain :
This pull request adds a link to the new feathers-authentication-keystone plugin which uses Openstack Keystone to authenticate a user in a feathersjs application and a typical howto.

Add feathers-authentication-keystone to ecosystem

---

guides/chat/processing.md

common-hooks link was not set, just added the relative target url

update missing link

---

api/events.md

Typo fixes

---

api/databases/querying.md

Ref https://github.com/feathersjs/feathers/issues/334#issuecomment-260834107:
> We will add documentation for searching to the adapters individually.

Add note about searching documents

---

ecosystem/readme.md

Add a link to an example repo that shows how to accomplish passwordless authentication by using the feathers-authentication-management library.

Added link to passwordless example in ecosystem.

---

ecosystem/readme.md

Added the subtitle "Caching" and a link to the plugin feathers-hooks-rediscache

Added feathers-hooks-rediscache

---

guides/step-by-step/basic-feathers/socket-client.md

Changing the code snippet from httpServerConfig to expressServerConfig to match the example code.

change httpServerConfig to expressServerConfig

---

guides/offline-first/optimistic-mutation.md

It could also be fixed by saying "what it ensures is rather different"

Awkward wording, probably wrong word

---

book.json

Related to #564 - this disables the search bar since it is broken anyway.

Disable search for now

---

README.md
book.json
package-lock.json
package.json

Deploy PDF build

---

api/hooks-common.md

Added a missing quotation mark.

Fix small typo

---

guides/step-by-step/basic-feathers/database-connector.md
guides/step-by-step/basic-feathers/hooks-1.md

Changelog:
- The example code using `users` object, but the explanation using `user` object
- Add missing Ajv dependencies in example Hooks

Fix some typo in documentation

---

api/databases/knexjs.md

related to https://github.com/feathersjs-ecosystem/feathers-knex/pull/124

add ilike operator

---

api/authentication/server.md
api/hooks-common.md
guides/step-by-step/basic-feathers/writing-hooks.md

fixes auth and common hooks broken links

links broken

---

SUMMARY.md
api/channels.md
api/events.md
faq/readme.md

Also updates related FAQs and removes the event filtering sections.

Add documentation for event channels

---

api/channels.md

The missing quote was breaking code coloring of the doc block

Add missing quote

---

SUMMARY.md
guides/migrating/buzzard.md
migrating/buzzard.md

Buzzard migration guide

---

guides/step-by-step/basic-feathers/hooks-1.md
guides/step-by-step/basic-feathers/hooks-2.md
guides/step-by-step/basic-feathers/rest-client.md
guides/step-by-step/basic-feathers/socket-client.md

Following the logic in #953 add file extension to all node calls in general feathers guide.

Update node calls to use file extension.

---

api/authentication/server.md
guides/auth/recipe.mixed-auth.md
guides/auth/recipe.oauth-basic.md

Change examples to match [the JWT spec](https://tools.ietf.org/html/rfc7519#section-5.1)

Fix typos: "type" --> "typ"

---

guides/auth/recipe.customize-jwt-payload.md

This note will save some troubles and questions in the slack channel on how to access the JWT payload in hooks

Add note on decoding JWT token

---

migrating.md

Fixed missing import for `protect` hook

Fixed missing import

---

guides/basics/real-time.md

1. Declare global io (defined in HTML) as global.
2. Rethrow any errors.

Make eslint happy

---

api/client/rest.md
api/services.md

Closes https://github.com/feathersjs/docs/issues/978, closes https://github.com/feathersjs/docs/issues/970

Fix broken links in REST client chapter

---

guides/chat/frontend.md

Fix typo in comment. 10 messages -> 25 messages

---

guides/basics/generator.md
guides/basics/hooks.md
guides/chat/authentication.md

Closes #981, closes #996, closes #984

Small tweaks to line up with the latest generator

---

api/services.md

Everything on a computer is automatic…
Also this blurb & section confuse me.
Also the MDN page about  async await doesn't enlighten the issue for me.

"automatically"

---

api/channels.md

```js
// user.rooms.forEach(room => app.channel(`rooms/${room.id}`).join(channel))
```
=>
```js
// user.rooms.forEach(room => app.channel(`rooms/${room.id}`).join(connection))
```

fix channels example comment

---

api/services.md

I fixed several obvious typos and adjusted some of the language for clarity. I added a link for `Promise` and styled `Promise` as code, with backticks, wherever it appears. I capitalized the first letters of bulleted items, except where inappropriate (e.g. code). Please make sure I didn't change anything that alters the original meaning or inaccurately represents the functionality. I don't think I did. I hope this helps!

Correct and improve grammar and language usage

---

api/channels.md

Closes https://github.com/feathersjs/docs/issues/961, closes https://github.com/feathersjs/feathers/issues/754, closes https://github.com/feathersjs/feathers/issues/744

Update channel documentation wit how to keep channels up to date

---

api/authentication/client.md

Fix spelling error on line 85, "Loged" -> "Logged"

Update client.md, spelling error

---

guides/chat/authentication.md

proposed minor change

---

api/client/rest.md

Update rest.md, spelling error

---

api/authentication/oauth2.md

settings was not defined (but script still did not work for me)

settings was not defined

---

SUMMARY.md
guides/chat/frontend.md
guides/chat/readme.md
guides/chat/testing.md

- Closes https://github.com/feathersjs/docs/issues/414
- Closes https://github.com/feathersjs/docs/issues/790

 Add a guide for testing the chat application

---

api/hooks.md
guides/basics/hooks.md
guides/basics/starting.md

I'm just getting into feathers and thus went through the basics guide (nice docs btw).
In the course of this I've find a typo (`contians` instead of `contains`) and some wording that could be improved (missing single quote & `a the` link)
This PR fixes it.

Fix typo & some wording

---

api/authentication/client.md

[authentication/client.md] fix spelling error

---

SUMMARY.md
api/authentication/server.md
guides/auth/recipe.express-middleware.md
package-lock.json

Related to https://github.com/feathersjs/authentication/issues/630
- Closes https://github.com/feathersjs/authentication/issues/619
- Closes https://github.com/feathersjs/authentication/issues/607
- Closes https://github.com/feathersjs/authentication/issues/617
- Closes https://github.com/feathersjs/authentication/issues/560
- Closes https://github.com/feathersjs/authentication/issues/469
- Closes https://github.com/feathersjs/feathers/issues/574

Add recipe showing how to authenticate Express middleware

---

api/express.md

There is a simple typo in the code sample.
Great documentation, keep it up!

fix resolve typo

---

api/client.md

The namespace should be @feathersjs instead of @feathers.

Fix typo of installing command into RN project.

---

guides/basics/databases.md

are you sure you need the comma here?

do you need a comma here?

---

guides/basics/rest.md

extremely minor spellilng error

extremely minor spelling error

---

api/databases/querying.md
faq/readme.md

Closes https://github.com/feathersjs/docs/issues/1049

Clarify search querying and move FAQ

---

guides/auth/recipe.oauth-basic.md

https://www.jokecamp.com/tutorial-passportjs-authentication-in-nodejs/
this tutorial suggests using callbackURL rather than successRedirect:
"You should not need to change the callbackURL. Just make sure it matches what you provided to GitHub."

changed successRedirect to callbackURL

---

api/express.md

As implemented via https://github.com/feathersjs/express/pull/20

Update documentation for updated API for @feathersjs/express

---

guides/basics/clients.md

Hi, I'm impressed with feathersjs from what I've seen so far! 
I noticed a few typos and sentences that could be improved.
Thanks,
Christian

Fix typos, clarify and simplify sentences

---

api/services.md

Thanks for the splendid framework 👍

fix type in services.md

---

api/client.md

I think this should be the last one for a while, as I should have the information I need to complete my next tasks. Thanks!

Fix typos and readability improvements

---

guides/chat/authentication.md

Hi, great job documenting Feathers. I hope you don't mind me proposing these minor improvements. I tried to make the sentences more concise and easier to digest at a glance. Thanks!

Fix typo (documentaion) and improve readability

---

guides/basics/rest.md

This is to be more concise with the rest of the material, later on we have `id: 0`, but having ++ before the currentId increments the variable before using it.

Changed ++this.currentId to this.currentId++

---

SECURITY.md

Fixes #1086

---

guides/chat/processing.md

When left-side navigation menu is collapsed, it's confusing to see no way how to get to the next step in the "What's next?' section.

Link from 'Processing data' to 'Building a frontend'

---

guides/chat/testing.md

I had to find this information in another package’s code (https://github.com/feathersjs/generator-feathers/blob/3b15d35458a121d87f35701712720e5e272625b9/lib/generator.js#L11) so adding it to the docs here for easier discovery in the future.

Instructions for changing the default test dir

---

guides/basics/real-time.md

Missing 'What's next?' section added.

Link from 'Real-time APIs' to 'Clients'

---

api/application.md

Add documentation for app.services

---

guides/chat/frontend.md

Removed a random script closing tag from the body of the index.html file

Updated the index.html body

---

api/authentication/server.md

Use express.static instead of feathers.static as per Buzzard

Fix server authentication setup example

---

api/client.md

Fixed a missing link and made the doc more obvious

Update create-react-app doc

---

guides/basics/real-time.md

From:
> In this chapter we added Socket.io transport and saw how to use channels to send events from server to client. In the next chapter we will look how to use browser Feathers application and client services to handle this events easily.
To:
> In this chapter we added the Socket.io transport and saw how to use channels to send events from server to client. In the next chapter we will look at how to use the browser Feathers application and client services to handle these events easily.

Fixed typo in "basics/real-time" #what's next

---

api/authentication/client.md

Make the config order more obvious.
I fell in this trap and lost an hour or two so I guess it deserves to be emphasized ^^ Sorry if the phrasing/terms are not quite precise though.

More precision about the auth setup/transport setup order

---

guides/basics/hooks.md

The change is in the last sentence of the paragraph :)

Reordering words for clarity.

---

api/authentication/oauth2.md

https://github.com/mrdj07/authentication-oauth2/pull/1

Update doc with custom oAuth error handler

---

guides/basics/rest.md

Fixed the wording of certain sentences. Thank you giving the world feathersJS!

Grammatical fixes in rest.md

---

guides/basics/generator.md

Update CLI version (current version as of writing is: 3.7.5)

Update generator.md CLI version

---

api/readme.md

Sorry, I was triggered. Really loving Feathers though!

Fixed a small typo

---

api/client.md

Closes https://github.com/feathersjs/feathers/issues/1015

Add documentation to include the debug module in transpilation

---

guides/chat/testing.md

An existing test is converted to run in a client/server environment.

Add a client/server test to the chat app.

---

guides/basics/real-time.md

Typo on "we can included"

---

guides/basics/databases.md

Where it says "a couple of" it should say "100"

Where it says "a couple of" it should say "100"

---

api/authentication/server.md

I'm bad at writing docs, but I tried.

Discuss manual JWT creation

---

guides/chat/testing.md

related to https://github.com/feathersjs/feathers-chat/pull/101
closes https://github.com/feathersjs/docs/issues/1235

Update coverage tool to NYC

---

api/authentication/oauth1.md
api/authentication/oauth2.md

Docs for https://github.com/feathersjs/feathers/pull/1124

Update docs for makeQuery

---

api/socketio.md

Closes https://github.com/feathersjs/feathers/issues/1223

Remove uws section from Socket.io documentation

---

api/authentication/jwt.md

Custom verifier JWT

---

guides/advanced/file-uploading.md

Sorry if this seems picky or annoying but I believe your wording to be misleading.
Your wording implied that an alternative to the `feathers-blob` module was being covered in this document which is not true. I hope this is clearer.

Altered misleading wording

---

api/hooks.md

This note would have saved me some hours figuring out how to get this up and running myself.
If I need to rephrase please let me know.

Adds a tip about app.hooks.js

---

api/configuration.md

Remove conf and directly use configuration(), change let for const since the app variable is never re-assigned. Remove the console.log of the configuration, since it would log 'function'.

Change example

---

api/express.md

Fixes a typo in the express docs.

Typo in express docs

---

guides/basics/authentication.md

Closes https://github.com/feathersjs/docs/issues/1339

Add TypeScript authentication code

---

api/hooks.md

Second example under asynchronous flow is missing async. Added that.

fix missing async in front of context

---

api/authentication/local.md

Made the same as the sentence below

Removed redundant words

---

help/faq.md

Fix for  `possible EventEmitter memory leak detected` warning was not clear to me, and maybe other people. I provide file that users can make change in, and outline the change itself.

added clarification for setMaxListeners

---

guides/basics/authentication.md
guides/basics/frontend.md
guides/basics/starting.md

Closes https://github.com/feathersjs/docs/issues/1367

Move rawgit.com references to feathers-chat package on unpkg.com

---

api/authentication/local.md

Fixes the LocalStrategy JavaScript and TypeScript customization code examples provided.

LocalStrategy customization code fix

---

guides/basics/services.md

Alphabetized and Added Missing Comma

Corrected TypeScript Example in services.md

---

.vuepress/config.js
api/authentication/service.md
cookbook/authentication/stateless.md

Closes https://github.com/feathersjs/docs/issues/1386

Cookbook entry for stateless JWT

---

api/authentication/client.md
api/authentication/hook.md
api/authentication/service.md

See https://github.com/feathersjs/feathers/pull/1708
- Closes https://github.com/feathersjs/docs/issues/1396
- Closes https://github.com/feathersjs/docs/issues/1401

Add parseStrategies and some clarification on authentication

---

api/authentication/oauth.md

See https://github.com/feathersjs/feathers/pull/1608/

Add information about dynamic oAuth redirects

---

api/channels.md

This is also in the generated channels.js file.

join(channel) should be join(connection)

---

api/authentication/service.md

Lots of online questions around this, and I finally found the answer from a personal blog (https://www.sitepoint.com/feathers-js-guide/) which shows the real flow.
I thought I send a PR 2 yrs ago for this, surprised by my bad memory, I forgot it again, haha :D 
If we can address it at  here at the official doc, could be much better!

Update auth flow for making things clear

---

api/authentication/jwt.md

Fixed an issue with the wrong service name in the example for JWT strategy implementation.

Fix error in JWT doc

---

README.md

https://github.com/feathersjs/website/pull/14

chore(docs): update intro readme text to be in line with homepage

---

api/client/rest.md

Documentation for - https://github.com/feathersjs/feathers/pull/1780

document ability to extend rest client to customise

---

.vuepress/config.js
cookbook/authentication/revoke-jwt.md

Closes https://github.com/feathersjs/feathers/issues/1336

Cookbook entry for revoking JWT

---

api/channels.md

Add some explanation for the core concepts around channels

---

.vuepress/config.js

feat: add DocSearch as recommended by vuepress

---

api/client.md
cookbook/express/file-uploading.md

fix: wrong imports for socketio

---

guides/basics/authentication.md

I got 'hung up' for a while thinking I needed to modify the server-side app.js while we need to create a new file for the client side.

Instruct tutorial-following-person to create a new file public/app.js

---

guides/basics/authentication.md
guides/basics/frontend.md
guides/basics/services.md

Also changes the name of `public/app.js` to `public/client.js`.
- Closes https://github.com/feathersjs/docs/issues/1477

Update chat app to use a display name oAuth to work without email

---

cookbook/authentication/Discord.md

Discord OAuth Strategy for Cookbook

Added DiscordStrategy

---

.vuepress/config.js

Added Discord.md to config.js

---

api/hooks.md

This is a follow-up to my PR in https://github.com/feathersjs/feathers/pull/2004

docs(hooks): add context.event description

---

cookbook/express/view-engine.md

- Closes https://github.com/feathersjs/feathers/issues/1786
- Closes https://github.com/feathersjs/feathers/issues/2078
- Closes https://github.com/feathersjs/feathers/issues/2061

Update Express view engine docs with authenticated sessions
