feathersjs/docs

middleware/error-handling.md

While prototyping, first thing most devs do is fire postman or curl and start hitting the rest api and might not know that they need to set `Accept: application/json` for feathers to send a json response.
https://github.com/feathersjs/feathers-mongoose/issues/56
https://feathersjs.slack.com/archives/general/p1457449015000948

Tip for getting json response instead of HTML

---

databases/sequelize.md

Since the user will choose between of the the available drivers from sequelize, installing pg pg-hstore is useless.

Unnecessary install of pg driver

---

databases/pagination.md

The documentation was incorrect (probably because it aws copied from the original NeDB and MongoDB behaviour).
Closes https://github.com/feathersjs/feathers-mongoose/issues/71

Fix documentation for $select

---

authentication/token.md

JWT is not encrypting/decrypting the payload, only validating whether it has been tampered with or not.

Remove encrypt/decrypt in place of sign

---

.editorconfig

To help keep uniform formatting.  Really only applies to .md files.  To help with the trailing whitespace commits.

Add a basic editorconfig

---

authorization/bundled-hooks.md

Sample code for `restrictToRoles` uses wrong method name (i.e. `restrictedToOwner`) instead of `restrictToRoles`.

Fixing wrong method name in sample code

---

authentication/client.md
clients/feathers.md
clients/rest.md
clients/socket-io.md
getting-started/scaffolding.md
guides/jquery.md
guides/react.md

This switches the docs to use feathers-client from npmcdn.com. This is a great change because it supports SemVer version ranges (like https://npmcdn.com/feathers-client@^1.0.0/dist/feathers.js) and we don't need to check in the distributables anymore.
@ekryski Can we change this on the homepage Gists as well?
Closes #120

Change feathers-client to npmcdn.com with version range

---

api/readme.md

Not sure how to test this correctly, but I tried to follow existing links I found in other chapters.

Fixed broken Services link in API chapter

---

clients/rest.md

So they `require` `feathers/client` rather than `feathers`

Update client snippets

---

authentication/readme.md

This update expands upon [the existing authentication documentation](http://docs.feathersjs.com/authentication/readme.html) based on my experience adding authentication to an existing Feathers app recently. When reading through the documentation initially it was not clear to me that a separate user service would need to be created or how to create new tokens once a user exists.
My goal here was to provide more detail for those whose entry point into the feathers-authentication module might be through this chapter in the book.
Changes include:
- Spelling out the first mention of "JWT" and linking it out to the project's site
- Mentioning the user service requirement at the top of the server-side section
- Adding missing `localEndpoint` server-side config options documentation
- Expanding …

Expand REST authentication docs

---

authentication/readme.md

This is a quick patch to update the default header value in client-side authentication configuration from `Authorization` to `authorization`. This change was made in feathersjs/feathers-authentication/pull/219 with the intent of normalizing the server- and client-side header defaults which should make the authentication module a little bit easier to use for anyone communicating with it over HTTP.
Blocked by feathersjs/feathers-authentication/pull/219.

Lowercase default client-side header

---

hooks/usage.md

Minor typo, bracket wasn't closed. Was probably missed because of the link bracket immediately before.

Missing bracket in hooks usage

---

why/showcase.md

I went through Feathers-related packages on NPM to get an idea of what was available. I updated the Community Plug-Ins doc with what I found. I tried not to include Featherjs packages mentioned within the docs, e.g. feathers-nedb.
The packages listed are of variable quality, so you might decide not to pull this.

Brought Community Plug-Ins listing up-to-date with NPM

---

getting-started/user-management.md

This tutorial instructs us to create a service called message, yet it shows the folder name for this service as messages. I changed the name to message.  There is another tutorial that uses the name messages, but not this one.

Change messages to message

---

clients/socket-io.md

Exaplanation included to the doc for a better example about timeout usage.

Updated the section related to service timeout

---

getting-started/user-management.md

Following the docs in `Your First App` very closely, in `User Management ~ Authorization` section, the code in `services/messages/hooks/index.js` contains this extra line, added here.
To clarify, `services/messages/hooks/index.js` presents with this extra line when the student first opens the file.

Missing line in hook code at this juncture of Your First App.

---

clients/vanilla-rest.md

After being totally confused as how to use operands like $le, $gt, $ne, etc. within a standard URL type GET request, decided to add a couple of examples to give people a basic idea.

More (simple) examples of using built-in operands

---

testing/readme.md

The names of the files generated by Feathers were not consistent with the ones in the documentation.
Before: user-models.js and menu-models.js
After: user-model.js and  menu-model.js

Make file names in doc consistent with feathers-cli

---

services/readme.md

I spent a bit of time trying to figure out why my service's `setup` method was not being called (in testing, and in interactive node.js sessions) when the service was registered.  Going into feather code, I realized that the service's `setup` is only called once `app.listen` is invoked.  I thought this clarification might be useful to others.

Clarify when a service's setup method is called.

---

hooks/common.md

- Validations section is very large. Removed text that offered little.
- Added anchors so the TOC links at top of doc work. Its very awkward
navigating this doc with links.
- Remove emphasis from Options subsections as they made it
visually harder to see the headers for each hook.
- Some text made more terse.

Improved common hooks doc

---

getting-started/setting-up.md

Fix breaking typo in docs

---

real-time/events.md

I ran into a situation in React where I had to register and unregister an event listener. I was familiar with the registering api (`service.on(...)`), but I didn't know about `service.removeListener(...)` until I got some help from @ekryski.
I figured it'd probably be good to have this in the docs.

[Events] Add 'Event Listener Lifecycle' section

---

getting-started/user-management.md

The image is not included in the generated template, and returns a 404.
It is also now consistent with the other html files.

Use correct ico file

---

hooks/common.md

Small typo when using the `setUpdatedAt` hook, which was shown as `setCreatedAt`.

Typo fix in setUpdatedAt hook

---

authentication/management.md

Just a small change, but I lost a lot of time because I've set `verifyChanges` field type to array of strings in my Sequelize/Postgres model and it didn't work at all. After looking over the source code I realized it does not use array of strings, but a key-value map. Setting column type to JSON solved the problem, but I think that description in docs is confusing, so I decided to create this PR.

Fixed description of verifyChanges field in authentication management

---

clients/feathers.md

Change `import io from 'socket.io-client/socket.io';` to `import io from 'socket.io-client';` as otherwise there's an error when importing the dependency. (At least from what I have been encountering when switching our app from rest client to socket client).
It's used as described in [official repo](https://github.com/socketio/socket.io-client#nodejs-server-side-usage) too.

Socket.io-client dependency import

---

databases/sequelize.md

It is not obvious where model registration should occur, so the file path should be specified, as it is in the proceeding steps.

Specify file path for model registration

---

api/application.md
api/databases/common.md
api/databases/knexjs.md
api/databases/localstorage.md
api/databases/memory.md
api/databases/mongodb.md
api/databases/mongoose.md
api/databases/nedb.md
api/databases/rethinkdb.md
api/databases/sequelize.md

Also making all the hook examples (where applicable) the array style syntax. I did this for 2 reasons:
1. To be more consistent
2. Because that is what the generator ships like and might reduce confusion for people.

Fixing some typos in the DB section

---

clients/feathers.md

https://docs.feathersjs.com/clients/feathers.html#usage-with-react-native mentions that a workaround is needed due to an issue in socket.io. This issue seems to have been resolved and pushed according to https://github.com/socketio/engine.io-parser/pull/55.
Just changed the text so that the workaround isn't mentioned.

Workaround for React Native no longer needed

---

ecosystem/README.md

This makes the Ecosystem plugins more accessible by bringing them into the left sidebar.  The list is huge, so this is very helpful to see how amazing our community is.  This is what it looks like:
Ideally, we could bold the headings that I've artificially bolded in the screenshot.  @eddyystop or @daffl is there a way to control this with the plugin you've made for the guides?

Make ecosystem plugins more accessible

---

SUMMARY.md
guides/frameworks/readme.md
guides/readme.md

This starts a page where we can keep track of framework guides and add them as they become available.  I've left placeholders for the guides that we already have.  I don't think we need to wait to merge this, though.

Auk framework guides

---

api/databases/elasticsearch.md

Also:
* add info about increasing test coverage
and including Elasticsearch 5.3
* add description for handling parent-child relationship
This changes are pertaining [PR#11](https://github.com/feathersjs/feathers-elasticsearch/pull/11) on feathers-elasticsearch.

docs(elasticsearch) add `$child` and `$parent` query description

---

api/hooks-common.md

`disableMultiItemChange` can only apply to `update`, `patch`, `remove`.

Fix disableMultiItemChange example

---

ecosystem/readme.md

I created a _Social Media_ category since this service didn't quite fit in any other category.

Adds `feathers-services-instagram-feed` to Ecosystem

---

api/authentication/oauth1.md
api/authentication/oauth2.md
api/authentication/server.md
api/databases/elasticsearch.md
api/databases/knexjs.md
api/databases/localstorage.md
api/databases/memory.md
api/databases/mongoose.md
api/databases/querying.md
api/databases/rethinkdb.md
api/events.md
api/express.md
ecosystem/readme.md
faq/readme.md
guides/advanced/creating-a-plugin.md
guides/advanced/using-a-view-engine.md
guides/readme.md
guides/step-by-step/basic-feathers/real-time.md

Removed redundant directory path (guides/guides) to fix link. Thankfully, at present, it only doesn't work rather than directing to 404 though I'm surprised Gitbook parsing didn't throw error. I imagine it assumes you're linking externally to some other md file which is hilariously unlikely if you ask me x)

Fixing old or broken links

---

faq/readme.md

This disappeared from the old docs, I think. I just took the text from https://github.com/feathersjs/feathers/pull/33

Add HTTPS setup to FAQs

---

guides/step-by-step/basic-feathers/rest-api-server.md

"email":"jane.doe@gmail.com","password":"X2y6","role":"admin","_id":"sbkXV7LVkMhx1NyY"
was
"email"::"jane.doe@gmail.com","password":"X2y6","role":"admin","_id":"sbkXV7LVkMhx1NyY"

Fixed the typo at Jane Doe

---

api/hooks-common.md

```javascript
// client
import { paramsForServer } from 'feathers-hooks-common';
service.patch(null, data, paramsForServer({
query: { dept: 'a' }, populate: 'po-1', serialize: 'po-mgr'
}));
// server
const { paramsFromClient } = require('feathers-hooks-common');
service.before({ all: [
paramsFromClient('populate', 'serialize', 'otherProp'), myHook
]});
// hook.params will now be
// { query: { dept: 'a' }, populate: 'po-1', serialize: 'po-mgr' } }
```

Added docs for paramsForServer utility and paramsFromClient hook func

---

api/databases/mongodb.md
api/databases/mongoose.md

see https://github.com/feathersjs/feathers-mongoose/issues/70#issuecomment-300336189

Added `upsert: true` to docs of `mongodb` and `mongoose`

---

guides/advanced/configuration.md

This is an issue I ran in to recently while setting up authentication.  As far as I can tell, it's not currently clearly documented anywhere that feathers-configuration will not process values that are escaped with backslashes.

Document env variable escaping

---

api/hooks-common.md

- `userInnerPopulate` [optional] Populate, when including records from a child service,
ignores any populate hooks defined for that child service.
The userInnerPopulate option will run those populate hooks.
This allows the populate for a base record to include child records
containing their own immediate child records,
without the populate for the base record knowing what those grandchildren populates are.

Documented the new useInnerPopulate option in populate hook

---

api/hooks-common.md

A common need is converting fields coming in from query params.
These fields are provided as string values by default and you may need them as numbers, boolenas, etc.
[`validateSchema`](#validateSchema) does a wide selection of [type coercions](https://github.com/epoberezkin/ajv/blob/master/COERCION.md), as well as checking for missing and unexpected fields.

Added FAQ: Coerce data types - the start of a FAQ section

---

api/client.md

As referenced in ['migrating to 1.0'](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md)

Update to feathers-authentication-client

---

ecosystem/readme.md

The feathers-mongoose-advanced readme says to use feathers-mongoose.
The feathers-mongoose-service github redirects to feathers-mongoose.
Removing both of these as they clutter the list and make the useful info harder to find.

Removing obsolete/nonexistent mongoose links

---

guides/frameworks/readme.md

The link to the feathers-vuex example app was broken.

Fix broken link

---

_layouts/website/page.html

This adds a legacy deprecation warning to each page of the old docs on https://legacy.docs.feathersjs.com and closes #673:

Add a legacy warning to each page

---

api/authentication/jwt.md
api/authentication/local.md

The docs are lacking how to authenticate via sockets without using `feathers-authentication-client`.  Please see this thread inside the `feathers-authentication` repo for more info: https://github.com/feathersjs/feathers-authentication/issues/523#issuecomment-310512114
This PR adds some documentation on how to achieve Local and JWT authentication using plain sockets.

Update authentication docs to add Direct Usage using sockets

---

api/databases/sequelize.md

Was reading through the example usage with sequelize and noticed that the variable name was incorrectly labelled as `sequelize` when it was obviously meant to be `service`.

Incorrect variable name

---

api/express.md

Tried to run this example and kept getting an error telling me that `configure` was not a method on `app`. Thought it was related to a change in Express 4.0. Realized that I'm a dummy and that the example code was missing a call to instantiate the app.

Missing call to instantiate in example

---

robots.txt

Since there isn't a one-to-one mapping from old to new docs they probably shouldn't show up in search results anymore.

Disable search engine crawling of legacy docs

---

examples/offline/package.json

The realtime-3 example requires `feathers-hooks-common` to run.

Added missing `feathers-hooks-common` dependency

---

api/databases/knexjs.md

The createQuery function is documented incorrectly as accepting a query object directly, where as it actually only accepts a params object (i.e. object of the shape `{ query: {...} }`.

Correct the call signature for createQuery

---

guides/about/features.md

Before a vowel one should use "an" instead of "a."

Grammar on About

---

ecosystem/readme.md

I've updated the link:
https://berndsgn.ch/angular2-and-feathersjs -> https://berndsgn.ch/observables-with-angular-and-feathersjs/

Fix link to Angular2 observables tutorial

---

guides/advanced/file-uploading.md

There is a good example for the file uploads as a standalone server.js file. There seemed to be lacking a version by which it is implemented by modifying the feathers generated service code.

 Add an example if used with the feather-cli service generator.

---

guides/auth/recipe.customize-jwt-payload.md

There is a typo in test prop beacuse before you customize the jwt with { test: 'test' }

Auth jwt recipe typo on test prop

---

guides/auth/readme.md

I had some trouble finding a good resource on auth documentation. After some days, I stumbled upon the API documentation, which seems to be the best resource as of now(?).
Adding this link might help others finding the documentation.

add link to auth api documentation

---

api/authentication/hooks.md

If you chose to use a single role per user as a string, it will work perfectly. The docs don't mention this. I found out about that it works after starting to fork this.

restrictToRoles handles singular string roles

---

migrating.md

Copying code results in an error due to small typo.   Adjusted to find correct package.

Small typo in client require

---

api/client.md

The default values of pingInterval and pingTimeout in Socket.io are longer than one minute and will fire warnings in React Native when using feathers-client with Socket.io. This commit adds instructions to the client docs on how to avoid these warnings properly.

Avoid long timeouts in React Native

---

guides/step-by-step/basic-feathers/rest-client.md

It might seems confusing to some (like myself just now) to have the server file here without the `.js` extension. While it runs fine I feel the guide will benefit from being easy to understand and keeping to a convention of explicitly stating file endings in node calls.

Add extension to executable JS.

---

guides/basics/hooks.md

The code sample under hooks will not compile without the reader first installing the Feathers error module. This makes that explicit and avoids an error on first run.

Explicitly mention Feathers error module install

---

guides/chat/processing.md

Following the code example, the property name is stated as `gravatar` when it’s `avatar` in the code. Updated the text to match the code.

Fix property name: it’s `avatar` not `gravatar`

---

guides/chat/readme.md

Remove redundant /guides fragment from the URLs.
(PS. It doesn’t look like the generator guide actually exists yet but it should be at the fixed URL when it does.)

Fix links to basics and generator guides

---

guides/basics/services.md

Just a small change to fix the spelling of `correspondingn` to `corresponding` on line 182 in `guides/basics/services.md`.

Fix spelling error

---

api/configuration.md

"When the NODE_ENV is not development" is not accurate. Even if NODE_ENV==='development' the `config/development.js`configuration will be loaded.

Update configuration.md to accurately reflect configuration behavior

---

guides/basics/rest.md

adding http:// to localhost:3030 makes it obviously a uri to humans and computers alike, so many terminals will make functioning links now.

update rest.md with obvious uri

---

api/authentication/server.md

fix app.configure(auth(options)) example

fix typo in server.md example

---

api/channels.md

As per the definition of `joinChannels`, parameters should be `user` and `connection`. Corrected the same in docs.

Fixed the parameters shown in example.

---

api/authentication/server.md

Adding a secondary example in case the developer wants to redirect the user on a failed authentication to a protected route.

Add failure redirect to authenticate example

---

api/client/rest.md

it is returning 404 for readme.md page. I think right doc path is adapters.md.

fix database adapters broken link

---

api/authentication/oauth2.md

This is necessary when the client and server reside on different domains.

Update docs about custom handler

---

guides/basics/hooks.md

This may have just been me, but I struggled to grok the "Registering Hooks" flow diagram. It wasn't until I gave up and scrolled passed that it became clear from context below. 
My recommendation here is to invert the order of the code/diagram and revise the wording.

Swap the order of the hook registry example and diagram

---

guides/basics/hooks.md

The hook execution diagram is appearing as inline code in the example code above it:
This change fixes that and embeds the diagram properly.

Fix broken inline hook execution diagram.

---

guides/basics/databases.md

It seems that the [databases chapter](https://docs.feathersjs.com/guides/basics/databases.html) doesn't actually demonstrate usage of NeDB with `feathers-nedb`. Unsure if this used to be detailed or if it hasn't been written up yet, but this PR might help remove some confusion.

Clarify databases chapter usage of NeDB.

---

api/express.md

This documentation update is for the pull request in [feathersjs/express](https://github.com/feathersjs/express/pull/25). It shows the added support for passing in a middleware array to `app.use` and includes a code example of how to use it.

Docs to allow multiple express mw functions to be passed into `app.use`

---

api/authentication/local.md

In a company project we recently had a bug that came down to the entityUsernameField's default value. I noticed that in the deprecated feathers-authentication-local package these options are documented. Also confirmed that the authentication-local plugin still checks for the presence of entity*Field options.

Add missing default options

---

guides/basics/hooks.md

[Link to section](https://docs.feathersjs.com/guides/basics/hooks.html#whats-next)
What do you think?
From:
`...can be used middleware for service method calls...`
To:
`...can be used as middleware for service method calls...`

Fixed typo in "Guides > The Basics > Hooks #What's next"

---

guides/basics/rest.md

[Link to section](https://docs.feathersjs.com/guides/basics/rest.html#rest-and-services)
First paragraph.
From:
> One of the goals of Feathers is make building REST APIs easier
To:
> One of the goals of Feathers is to make building REST APIs easier

Fixed typo in rest.md #rest-and-services

---

guides/basics/rest.md

[Link to section](https://docs.feathersjs.com/guides/basics/rest.html#rest-apis)
Second paragraph.
From:
> This what Feathers transports do.
To:
> This is what Feathers transports do.

Fixed typo in rest.md

---

guides/basics/real-time.md

I think the following:
> Channels determine which real-time events should be sent to which client. For example, we want to only send messages to authenticated users or users in the same room. For this example we will just enable real-time functionality for all connections however:
Can be changed to:
> Channels determine which real-time events should be sent to which client. For example, we might want to only send messages to authenticated users or users in the same room. For this example however, we will just enable real-time functionality for all connections:
Thoughts?

Grammar suggestion

---

api/hooks.md

The present text is ambiguous.

Clarify after hooks are still run when SKIP is returned in a before hook

---

api/configuration.md

It mentions the file as ` .js` but it's actually a json file.
(otoh, it'd be amazing to have a js configuration example in this page).

Fix reference to env-specific config file

---

guides/basics/generator.md

The feathers-memory library is no longer needed in this app.js example because the library is now used in the messages service.

Update app.js example using messages service

---

api/authentication/server.md

Property that seems to be required but is not mentioned in the docs in the authentication options
From [jsonwebtokens](https://github.com/auth0/node-jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback)
`secretOrPrivateKey` is a string, buffer, or object containing either the secret for HMAC algorithms or the PEM encoded private key for RSA and ECDSA. In case of a private key with passphrase an object { key, passphrase } can be used (based on crypto documentation), in this case be sure you pass the algorithm option.

Added 'secret' property for authentication options

---

api/authentication/local.md

The password field didn't get protected in the documentation example.
The local.hooks.protect hook must be an global after hook and not an after.create one.
The [feathersjs-authentication README](https://github.com/feathersjs/authentication/blob/master/README.md) is already correct but this documentation was not.

Fix documentation error about local.hooks.protect

---

guides/chat/service.md

The curl had a name field which the scaffolded `messages` service does not have. Fix the curl.

Fix curl for scaffolded service

---

api/errors.md

Fixed the typo `inclue`, grammar mistake (i.e. missing closing comma of the parenthetical phrase `all of which are instances of FeathersError`) and semantic errors (confusing and mistyping `i.e.` with `e.g.`).

Small corrections

---

.vuepress/config.js
.vuepress/styles/index.styl
api/client/primus.md
api/client/rest.md
api/client/socketio.md
api/services.md
guides/basics/services.md
package-lock.json
package.json

In the crow docs there are still codeblocks from the old gitbook that are "breaking" the documentation.
I added an existent vuepress plugin to add tab support and used it to replace all occurences of codeblocks.
I did not add any additional styling.

Use vuepress tabs plugin and replace gitbook codetabs usages

---

api/authentication/oauth.md

Added a note to the authenticate via an already obtained oauth access token flow description to remind prospective users that they need to add the given oauth strategy to their `authStrategies` config.

Add note to "authenticate via existing token" flow

---

guides/basics/hooks.md

Changed 'context.data.text' to 'data.text' on some examples. Since data is already destructured before, 'context.' is not needed.
edit: thanks to @w3cj, actual suggestion came from him while he was streaming 'going through the getting started guide'

update examples to use destructured variables

---

cookbook/authentication/facebook.md

Without the scope, the piece of code will not return the email property.

Add required scope to configuration

---

cookbook/authentication/facebook.md

Class name instantiated is not the same name as the one used to define the class.

update FacebookStrategy class name

---

api/hooks.md

Fixed a text displaying `__` instead of beeing bold

Fix non-bold text in hooks docs

---

api/client/rest.md

This part of the documentation was a little misleading. You DON'T need a websocket setup to be able to receive real-time events from the server. The real-time transports via socketio or primus can fallback to http polling in the cases when a websocket connection can not be established. So you can use a realtime transport even if you have some proxy or some other kind network restriction that won't allow a websocket connection.

Clarify info about real-time events

---

api/authentication/oauth.md

A few default values for the oauth config were backticked but not quoted, which made it confusing as to whether they were strings or references to other properties.
I also updated the default value for `callback` since it gets its value from `defaults.path`.

Use quotes to indicate string values

---

api/services.md

Provides a fix for the Feathers service code example to better reflect what the Feathers CLI generates for a newly scaffold-ed app, and adds a ProTip to help with documentation.

Feathers Service code example fix

---

api/authentication/client.md

As discussed [here](https://github.com/feathersjs/docs/issues/1397), this pull request attempts to clarify that it’s safe to call `app.reAuthenticate()` if necessary, but it shouldn’t be called for _every_ request and only very rarely needs to be called more than  once.
Closes https://github.com/feathersjs/docs/issues/1397

Clarify the note on calling `app.reAuthenticate()`

---

api/client/rest.md

This has been possible for a long time already, just adding some better docs.
Closes https://github.com/feathersjs/feathers/issues/1102

Document usage of multiple REST clients

---

cookbook/express/file-uploading.md

The Feathers cookbook for file uploads includes a code snippet where NeDB is imported, alongside an explanation for doing so. However, the dependency is never used and may cause confusion to users. It threw me for a bit of a loop. 😅
If this snippet does indeed belong here - perhaps we could refactor to make it more clear where it is necessary? I'd be more than happy to submit an updated PR if this is the case. 👍

Remove NeDB reference in code snippets for file uploads

---

guides/migrating.md

The link to the hooks common library documentation in the SKIP section point to the old domain.

fix(docs): SKIP, change link of hooks-common library docs

---

guides/basics/testing.md

Relates to https://github.com/feathersjs/docs/issues/1452 
Having a space before the & adds that space at the end of the variable. The NODE_ENV is then set to "test " which is unexpected.

Corrected typo for windows users

---

cookbook/authentication/facebook.md

fixes the param name at `FacebookStrategy` `get profile` function:
When I was reading the docs, just copied the snippet `FacebookStrategy` from the TS docs, suddenly I found this inconsistency this PR
- Duplicated identifier (`data`) 
- Also `authResult` does not exists in this scope

Fixing param name at FacebookStrategy TS

---

guides/frameworks.md

The current link for Vue integration leads to https://github.com/feathers-plus/feathers-chat-vuex repository which is outdated and not maintained anymore. The recent repo for the current version of FeathersVuex is at https://github.com/feathersjs-ecosystem/feathers-chat-vuex.

Update the repo address for Feathers + Vue integration

---

.vuepress/config.js

👋 team,
I am working on DocSearch. [We have an integration for Vuepress](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search). We thought it is a shame you can not also used this search that you can [find on vuejs for example](https://vuejs.org/).
This PR will add DocSearch to the documentation website. It will allow a user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
Let me know if you need anything.

feat: add DocSearch as recommended by vuepress

---

api/configuration.md

Added important detail that when using @feathers/configuration,  app.get() can't directly access nested properties. 
https://github.com/feathersjs-ecosystem/configuration/issues/38
I stumbled upon this unexpected behavior and spent some time debugging the issue. Having worked with node-config for some time I just expected nested properties to work just as well with `app.get()`/`app.set()` as with `config.get()`/`config.set()`.

Updated configuration docs for nested properties

---

api/client.md

Bumped up FeathersJS and SocketIO client to the latest version in "Load from CDN with <script>" section.
I was experimenting with custom events. I just copied the snippet from the [documentation](https://docs.feathersjs.com/api/client.html#load-from-cdn-with-script). But, when I tried to call `app.reAuthenticate()` it didn't work. Then I noticed that I am importing old version (`3.0.0`) of Feathers client (_the `^` in the URL didn't import the latest one_). So, I changed the version to the latest (`4.5.7`) one and it worked as expected. I've updated the version of socketio as well (`1.7.3` to `2.3.0`).

Bumped up feathers & socketio client version

---

api/authentication/client.md
api/authentication/oauth.md
api/authentication/readme.md
api/authentication/service.md
api/readme.md
cookbook/authentication/_discord.md
cookbook/authentication/auth0.md
cookbook/authentication/facebook.md
guides/basics/authentication.md
guides/migrating.md

There are several instances of the docs referencing both `oAuth` and `OAuth`.
This PR changes all references to `OAuth`: https://en.wikipedia.org/wiki/OAuth

fix: use consistent reference to OAuth

---

api/databases/common.md

Currently, the only place learn about hook-less service method is at https://docs.feathersjs.com/guides/migrating.html#hook-less-service-methods and it isn't obvious when looking through the docs..
I have added it to `api/databases/common` at the top after `constructor` but not sure if it should be at the bottom after `adapter.remove(id, params)`. What do you think?
This was brought up by Mike from slack...

docs: add hook-less service method description

---

cookbook/authentication/anonymous.md

This can be obvious when looking at docs side-by-side with you application's code, but for people just browsing the documentation it can be confusing now knowing where `authentication` was defined, only that there was a likely global object with a `register` method that was used to add an auth strategy.

Show in snippets where `authentication` is defined
